{
  "regions":[
		{"name":"New England","cumulative":5560, "id":1},
		{"name":"West South Central","cumulative":23003, "id":2},
		{"name":"Pacific","cumulative":66974, "id":3},
		{"name":"Middle Atlantic","cumulative":75208, "id":4},
		{"name":"East South Central","cumulative":95208, "id":5},
		{"name":"Mountain","cumulative":193343, "id":6},
		{"name":"West North Central","cumulative":277347, "id":7},
		{"name":"East North Central","cumulative":452921, "id":8},
		{"name":"South Atlantic","cumulative":736424, "id":9}
	],
	"states":[
		{"name": "Alabama","abbreviation": "AL", "region": 5, "count":95208},
    	{"name": "Arizona", "abbreviation": "AZ", "region": 6, "count":193343},
   		{"name": "Arkansas","abbreviation": "AR", "region": 2, "count":23003},
    	{"name": "California", "abbreviation": "CA", "region": 3, "count":66974},
   		{"name": "Colorado","abbreviation": "CO", "region": 6, "count":193343},
    	{"name": "Connecticut","abbreviation": "CT", "region": 1, "count":75208},
    	{"name": "Delaware", "abbreviation": "DE", "region": 9, "count":736424},
    	{"name": "Florida","abbreviation": "FL", "region": 9, "count":736424},
    	{"name": "Georgia", "abbreviation": "GA", "region": 9, "count":736424},
		{"name": "Idaho","abbreviation": "ID", "region": 6, "count":193343},
    	{"name": "Illinois", "abbreviation": "IL", "region": 8, "count":452921},
    	{"name": "Indiana","abbreviation": "IN", "region": 8, "count":452921},
    	{"name": "Iowa","abbreviation": "IA", "region": 7, "count":277347},
    	{"name": "Kansas", "abbreviation": "KS", "region": 7, "count":277347},
    	{"name": "Kentucky", "abbreviation": "KY", "region": 5, "count":95208},
    	{"name": "Louisiana", "abbreviation": "LA", "region": 2, "count":23003},
    	{"name": "Maine", "abbreviation": "ME", "region": 1, "count":5560},
    	{"name": "Maryland","abbreviation": "MD", "region": 9, "count":736424},
    	{"name": "Massachusetts","abbreviation": "MA", "region": 1, "count":75208},
    	{"name": "Michigan","abbreviation": "MI", "region": 8, "count":452921},
    	{"name": "Minnesota", "abbreviation": "MN", "region": 7, "count":277347},
    	{"name": "Mississippi","abbreviation": "MS", "region": 5, "count":95208},
    	{"name": "Missouri","abbreviation": "MO", "region": 7, "count":95208},
    	{"name": "Montana","abbreviation": "MT", "region": 6, "count":95208},
    	{"name": "Nebraska","abbreviation": "NE", "region": 7, "count":277347},
    	{"name": "Nevada","abbreviation": "NV", "region": 6, "count":193343},
    	{"name": "New Hampshire","abbreviation": "NH", "region": 1, "count":5560},
    	{"name": "New Jersey", "abbreviation": "NJ", "region": 4, "count":75208},
    	{"name": "New Mexico","abbreviation": "NM", "region": 6, "count":193343},
    	{"name": "New York","abbreviation": "NY", "region": 4, "count":75208},
    	{"name": "North Carolina","abbreviation": "NC", "region": 9, "count":736424},
    	{"name": "North Dakota","abbreviation": "ND", "region": 7, "count":95208},
    	{"name": "Ohio","abbreviation": "OH", "region": 8, "count":452921},
    	{"name": "Oklahoma", "abbreviation": "OK", "region": 2, "count":23003},
    	{"name": "Oregon","abbreviation": "OR", "region": 3, "count":66974},
    	{"name": "Pennsylvania","abbreviation": "PA", "region": 4, "count":75208},
    	{"name": "Rhode Island","abbreviation": "RI", "region": 1, "count":5560},
    	{"name": "South Carolina", "abbreviation": "SC", "region": 9, "count":736424},
    	{"name": "South Dakota", "abbreviation": "SD", "region": 7, "count":277347},
    	{"name": "Tennessee", "abbreviation": "TN", "region": 5, "count":95208},
    	{"name": "Texas", "abbreviation": "TX", "region": 2, "count":23003},
    	{"name": "Utah","abbreviation": "UT", "region": 6, "count":193343},
    	{"name": "Vermont","abbreviation": "VT", "region": 1, "count":5560},
    	{"name": "Virginia","abbreviation": "VA", "region": 9, "count":736424},
    	{"name": "Washington", "abbreviation": "WA", "region": 3, "count":66974},
    	{"name": "West Virginia","abbreviation": "WV", "region": 9, "count":736424},
    	{ "name": "Wisconsin", "abbreviation": "WI", "region": 8, "count":452921},
    	{"name": "Wyoming","abbreviation": "WY", "region": 6, "count":193343}
	]
}